#!/usr/bin/env perl

use feature ":5.10";
use strict;
use warnings;

my $result = look_and_say_n_times($ARGV[0], $ARGV[1]);
say length($result);

sub look_and_say_n_times {
  my ($string, $count) = @_;

  while($count-- > 0) {
    $string =~ s/((.)\2*)/length($1) . $2/ge;
  }

  $string;
}
